pipeline {
    agent any
    stages{
        stage("Clean Up"){
            steps{
                deleteDir()
            }
        }
        stage("Clone Repo"){
            steps{
                sh "git clone https://github.com/kushagra4321gkp-droid/JobApp.git"
            }
        }
        stage("Build"){
            steps{
                dir("JobApp"){
                    sh "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("JobApp"){
                    sh "mvn test"
                }
            }
        }
    }
}